#Test against this version of Node.js
environment:
matrix:
# node.js
- nodejs_version: "6"

# Install scripts.
install:
#get latest stable version of Node.ks
-ps: Install-Product node $:nodejs_version
#install modules
-npm install

test_script:
- node --version
- npm --version
- npm test

build: off
